name: Telegraph PDF Uploader

on:
  workflow_dispatch:
    inputs:
      pdf_url:
        description: "Enter the PDF download link (optional)"
        required: false
        type: string

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install natsort aiofiles telegraph pillow httpx requests PyMuPDF

      - name: Run Telegraph uploader
        run: python main.py
        env:
          PDF_URL: ${{ github.event.inputs.pdf_url }}
